#  ⌜                                          ⌝
#    See available configurations at:
#    https://skaffold.dev/docs/references/yaml
#  ⌞                                          ⌟
---
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: apps
deploy:
  helm:
    releases:
      # ===[Deployment: App.Ingress]===
      - name: app-ingress
        repo: https://kubernetes.github.io/ingress-nginx
        remoteChart: ingress-nginx
        version: 4.0.17
        createNamespace: true
        namespace: ingress
profiles:
  - name: build
  - name: development
  - name: production
