---
arrowParens: "always"
bracketSpacing: true
endOfLine: "lf"
printWidth: 80
proseWrap: "always"
semi: true
singleQuote: false
tabWidth: 2
trailingComma: "all"
useTabs: true
# @trivago/prettier-plugin-sort-imports
importOrderGroupNamespaceSpecifiers: true
importOrderCaseInsensitive: true
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrder:
  - <THIRD_PARTY_MODULES>
  - ^@eden\/(.*)$
  - ^\$((?!ts|utils).)*$
  - ^\$(.*)$
  - ^\.\/(.*)\.((?!animator|controller|observer|view).)*$
  - ^[./]
importOrderParserPlugins:
  - typescript
  - jsx
  - classProperties
  - decorators-legacy

overrides:
  - files:
      - "*.json"
    options:
      useTabs: false
  - files:
      - "*.yaml"
      - "*.yml"
    options:
      printWidth: 9999
