/**
 * Two-dimensional positions.
 */
export enum Position {
	BOTTOM = "BOTTOM",
	BOTTOM_LEFT = "BOTTOM_LEFT",
	BOTTOM_RIGHT = "BOTTOM_RIGHT",
	LEFT = "LEFT",
	LEFT_BOTTOM = "LEFT_BOTTOM",
	LEFT_TOP = "LEFT_TOP",
	RIGHT = "RIGHT",
	RIGHT_BOTTOM = "RIGHT_BOTTOM",
	RIGHT_TOP = "RIGHT_TOP",
	TOP = "TOP",
	TOP_LEFT = "TOP_LEFT",
	TOP_RIGHT = "TOP_RIGHT",
}
