import { UniversalRenderProps } from ".";

/**
 * Infers the data structure of the data generated by the universal component.
 * This data is then transformed via the `InjectedUniversalData` type signature
 * and injected to the desired component via `Universal.enhance`.
 */
export type InferUniversalDataFromProps<TProps> =
	TProps extends UniversalRenderProps<infer TData> ? TData : never;
