import { UniversalComponent, UniversalRenderProps } from ".";

/**
 * Signature for data structure generated by a universal component.
 */
export type UniversalComponentData<TComponent> =
	TComponent extends UniversalComponent<infer TProps>
		? TProps extends UniversalRenderProps<infer TData>
			? TData
			: never
		: never;
