// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: eden/account/account.proto

package account

import (
	_ "eden.account/api/eden/db"
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	_ "google.golang.org/protobuf/types/descriptorpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
