org: samcraigdev
app: taygo
service: taygo-contact
provider:
  name: aws
  ecr:
    images:
      contact:
        path: ./
        file: ./.docker/.build.dockerfile
        buildArgs:
          TOOLS_GOLANG_VERSION: ${env:TOOLS_GOLANG_VERSION}

functions:
  contact:
    image:
      name: contact
plugins:
  - serverless-offline
custom:
  serverless-offline:
    useDocker: true
